;;; templ-ts-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from templ-ts-mode.el

(autoload 'templ-ts-mode "templ-ts-mode" "\
Major mode for editing Templ files.

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.templ\\'" . templ-ts-mode))
(register-definition-prefixes "templ-ts-mode" '("templ-ts-"))

;;; End of scraped data

(provide 'templ-ts-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; templ-ts-mode-autoloads.el ends here
